Fix a test failure with Rails8.1
Fix the following error that occurred when running tests with Rails 8.1

```
An error occurred while loading spec_helper.
Failure/Error: require 'rails/railtie'

NoMethodError:
  undefined method `delegate_missing_to' for class Rails::Initializable::Collection
# ./vendor/bundle/ruby/3.3.0/gems/railties-8.1.1/lib/rails/initializable.rb:41:in `<class:Collection>'
# ./vendor/bundle/ruby/3.3.0/gems/railties-8.1.1/lib/rails/initializable.rb:37:in `<module:Initializable>'
# ./vendor/bundle/ruby/3.3.0/gems/railties-8.1.1/lib/rails/initializable.rb:6:in `<module:Rails>'
# ./vendor/bundle/ruby/3.3.0/gems/railties-8.1.1/lib/rails/initializable.rb:5:in `<top (required)>'
# ./vendor/bundle/ruby/3.3.0/gems/railties-8.1.1/lib/rails/railtie.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:3:in `<top (required)>'
```